services:

  manual-portal-front:
    image: manual-portal-front
    container_name: manual-portal-front
    hostname: manual-portal-front
    restart: always
    ports:
      - "4321:4321"
    volumes:
      - ./content:/app/src/content
    networks:
      - manual-portal-network


  manual-portal-cms-tina:
    image: manual-portal-cms-tina
    container_name:  manual-portal-cms-tina
    hostname:  manual-portal-cms-tina
    restart: always
    user: "1001:1001"
    depends_on:
    - manual-portal-front
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    volumes:
    - ./content:/app/content
    networks:
      - manual-portal-network


  manual-portal-mongo-tina:
    image: mongo
    container_name: manual-portal-mongo-tina
    hostname: manual-portal-mongo-tina
    restart: always
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tina-startlight
    command: 
      - "--bind_ip_all"  # Permite conexiones externas
      - "--auth"         # Habilita autenticación
    volumes:
      - ./dataDB:/data/db
    networks:
      - manual-portal-network


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 7081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: tina-startlight
      ME_CONFIG_MONGODB_URL: mongodb://root:tina-startlight@manual-portal-mongo-tina:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - manual-portal-network

networks:
  manual-portal-network:
